[package]
name = "kvs"
version = "0.1.0"
authors = ["wangzizheng <james.wang0057@gmail.com>"]
description = "A key-value store"
edition = "2021"

[dependencies]
clap = "2.34.0"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
